"""Tests for the web export: question rows, the atlas document and the planner parity fixtures."""

import json

import pytest

from gate_atlas.config import PAPER_YEARS, PROCESSED_DIR
from gate_atlas.dataset import load_questions
from gate_atlas.planner.units import load_units
from gate_atlas.tagging.text import load_items
from gate_atlas.web_export import FIXTURES_DIR, SIMILAR_COUNT, atlas_document, planner_fixtures, question_rows

MARKS_PER_PART = {"DA": 85, "GA": 15}


@pytest.fixture(scope="module")
def records() -> list[dict]:
    """All question records of the dataset."""
    return load_questions()


@pytest.fixture(scope="module")
def items() -> list[dict]:
    """All syllabus items."""
    return load_items()


def test_question_rows_cover_every_question_with_crop_and_neighbours(records: list[dict]) -> None:
    """Every question is exported once, with an existing crop and up to five same-part neighbours."""
    rows = question_rows(records)
    assert [r["id"] for r in rows] == [r["id"] for r in records]
    part = {r["id"]: r["part"] for r in rows}
    for row in rows:
        assert (PROCESSED_DIR / row["crop"]).is_file(), row["crop"]
        neighbours = row["similar"]
        assert 0 < len(neighbours) <= SIMILAR_COUNT
        assert all(other != row["id"] and part[other] == row["part"] for other, _ in neighbours)
        scores = [score for _, score in neighbours]
        assert scores == sorted(scores, reverse=True)


def test_atlas_document_conserves_marks_and_lists_each_question_once(records: list[dict], items: list[dict]) -> None:
    """Item marks add up to each paper's part totals, and each question is listed under exactly one item."""
    document = atlas_document(records, items, load_units(records, items))
    assert set(document["items"]) == {i["id"] for i in items}
    for k, year in enumerate(PAPER_YEARS):
        for part, total in MARKS_PER_PART.items():
            marks = sum(stats["marks"][k] for item_id, stats in document["items"].items() if item_id.startswith(f"{part}."))
            assert marks == total, (year, part, marks)
    listed = [qid for stats in document["items"].values() for qid in stats["questions"]]
    assert sorted(listed) == sorted(r["id"] for r in records)


def test_committed_planner_fixtures_match_the_python_planner(records: list[dict], items: list[dict]) -> None:
    """The TypeScript parity fixtures were generated by the current Python planner (re-run export-web if not)."""
    committed = json.loads((FIXTURES_DIR / "plans.json").read_text(encoding="utf-8"))
    fresh = json.loads(json.dumps(planner_fixtures(load_units(records, items))))
    assert committed["cases"] == fresh
